name: Make Release / Publish to OSS / Promote to Maven Central

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/v}" >> $GITHUB_ENV

      - name: Print information
        run: echo "Version ${{ env.RELEASE_VERSION }}"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.0.0

      - name: Build / Upload to OSS sonatype / Promote to Maven Central
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: |
          gradle --info --stacktrace \
            -Pversion=${{ env.RELEASE_VERSION }} \
            -Psigning.password=${{ secrets.GPG_SIGNING_PASSWORD }} \
            -PossrhUsername=kochetkov-ma \
            -PossrhPassword=${{ secrets.ossrhPassword }} \
            -x test publish createRepository closeAndReleaseRepository \
            --no-build-cache --rerun-tasks